/// 시설정보 항목을 컨텐츠타입별로 확정하기 전, detailCommon2/detailIntro2
/// 원본 응답을 필드 단위로 그대로 확인하기 위한 임시 디버그용 라벨 매핑.
///
/// 컨텐츠타입별 시설정보 항목이 정해지면 spot_detail_screen.dart의
/// 시설정보 섹션과 함께 이 파일도 삭제(또는 확정된 필드만 남기고 정리)한다.
library;

/// detailCommon2 필드명 -> 한글명. contentTypeId와 무관하게 항상 동일한 필드.
const Map<String, String> kCommonFieldLabelsDebug = {
  'contentid': '콘텐츠ID',
  'contenttypeid': '콘텐츠타입ID',
  'title': '제목',
  'createdtime': '등록일',
  'modifiedtime': '수정일',
  'tel': '전화번호',
  'telname': '전화번호명',
  'homepage': '홈페이지(HTML)',
  'booktour': '교과서 속 여행지 여부',
  'firstimage': '대표이미지(원본)',
  'firstimage2': '대표이미지(썸네일)',
  'cpyrhtDivCd': '저작권 유형',
  'mapx': '좌표(경도)',
  'mapy': '좌표(위도)',
  'mlevel': '지도 확대레벨',
  'areacode': '지역코드',
  'sigungucode': '시군구코드',
  'cat1': '대분류코드',
  'cat2': '중분류코드',
  'cat3': '소분류코드',
  'addr1': '주소',
  'addr2': '상세주소',
  'zipcode': '우편번호',
  'overview': '개요설명',
  'lDongRegnCd': '법정동 지역코드',
  'lDongSignguCd': '법정동 시군구코드',
  'lclsSystm1': '분류체계 대분류',
  'lclsSystm2': '분류체계 중분류',
  'lclsSystm3': '분류체계 소분류',
};

/// detailIntro2 필드명 -> 한글명. contentTypeId별로 실제 내려오는 필드가 다르다.
const Map<String, String> kIntroFieldLabelsDebug = {
  // 12 관광지
  'heritage1': '세계문화유산 지정여부',
  'heritage2': '세계자연유산 지정여부',
  'heritage3': '세계기록유산 지정여부',
  'infocenter': '문의 및 안내',
  'opendate': '개장일',
  'restdate': '쉬는날',
  'expguide': '체험안내',
  'expagerange': '체험가능연령',
  'accomcount': '수용인원',
  'useseason': '이용시기',
  'usetime': '이용시간',
  'parking': '주차시설',
  'chkbabycarriage': '유모차 대여 정보',
  'chkpet': '애완동물 동반 가능 정보',
  'chkcreditcard': '신용카드 가능 정보',
  // 14 문화시설
  'scale': '규모',
  'usefee': '이용요금',
  'discountinfo': '할인정보',
  'spendtime': '관람 소요시간',
  'parkingfee': '주차요금',
  'infocenterculture': '문의 및 안내',
  'accomcountculture': '수용인원',
  'usetimeculture': '이용시간',
  'restdateculture': '쉬는날',
  'parkingculture': '주차시설',
  'chkbabycarriageculture': '유모차 대여 정보',
  'chkpetculture': '애완동물 동반 가능 정보',
  'chkcreditcardculture': '신용카드 가능 정보',
  // 15 축제/공연/행사
  'sponsor1': '주최자 정보',
  'sponsor1tel': '주최자 연락처',
  'sponsor2': '주관사 정보',
  'sponsor2tel': '주관사 연락처',
  'eventenddate': '행사 종료일',
  'playtime': '공연시간',
  'eventplace': '행사 장소',
  'eventhomepage': '행사 홈페이지',
  'agelimit': '관람 가능연령',
  'bookingplace': '예매처',
  'placeinfo': '행사장 위치안내',
  'subevent': '부대행사',
  'program': '행사 프로그램',
  'eventstartdate': '행사 시작일',
  'usetimefestival': '이용요금',
  'discountinfofestival': '할인정보',
  'spendtimefestival': '관람 소요시간',
  'festivalgrade': '축제 등급',
  'festivaltype': '축제 종류',
  // 28 레포츠
  'openperiod': '개장기간',
  'reservation': '예약안내',
  'infocenterleports': '문의 및 안내',
  'scaleleports': '규모',
  'accomcountleports': '수용인원',
  'restdateleports': '쉬는날',
  'usetimeleports': '이용시간',
  'usefeeleports': '이용요금',
  'expagerangeleports': '체험가능연령',
  'parkingleports': '주차시설',
  'parkingfeeleports': '주차요금',
  'chkbabycarriageleports': '유모차 대여 정보',
  'chkpetleports': '애완동물 동반 가능 정보',
  'chkcreditcardleports': '신용카드 가능 정보',
  // 32 숙박
  'roomcount': '객실수',
  'roomtype': '객실유형',
  'refundregulation': '환불규정',
  'checkintime': '입실시간',
  'checkouttime': '퇴실시간',
  'chkcooking': '취사 가능 여부',
  'seminar': '세미나실 여부',
  'sports': '스포츠시설 여부',
  'sauna': '사우나실 여부',
  'beauty': '뷰티시설 여부',
  'beverage': '식음료장 여부',
  'karaoke': '노래방 여부',
  'barbecue': '바비큐장 여부',
  'campfire': '캠프파이어 여부',
  'bicycle': '자전거 대여 여부',
  'fitness': '헬스장 여부',
  'publicpc': '공용 PC실 여부',
  'publicbath': '공용 욕실 여부',
  'subfacility': '부대시설 정보',
  'foodplace': '식당 정보',
  'reservationurl': '예약안내 홈페이지',
  'pickup': '픽업 서비스 여부',
  'infocenterlodging': '문의 및 안내',
  'parkinglodging': '주차시설',
  'reservationlodging': '예약안내',
  'scalelodging': '규모',
  'accomcountlodging': '수용가능인원',
  // 38 쇼핑
  'saleitem': '판매 품목',
  'saleitemcost': '판매 품목별 가격대',
  'fairday': '장서는 날',
  'opendateshopping': '개장일',
  'shopguide': '매장 안내',
  'culturecenter': '문화센터 바로가기',
  'restroom': '화장실 설명',
  'infocentershopping': '문의 및 안내',
  'scaleshopping': '규모',
  'restdateshopping': '쉬는날',
  'parkingshopping': '주차시설',
  'chkbabycarriageshopping': '유모차 대여 정보',
  'chkpetshopping': '애완동물 동반 가능 정보',
  'chkcreditcardshopping': '신용카드 가능 정보',
  'opentime': '영업시간',
  // 39 음식점
  'seat': '좌석 수',
  'kidsfacility': '어린이 놀이방 여부',
  'firstmenu': '대표 메뉴',
  'treatmenu': '취급 메뉴',
  'smoking': '금연/흡연 여부',
  'packing': '포장 가능 여부',
  'infocenterfood': '문의 및 안내',
  'scalefood': '규모',
  'parkingfood': '주차시설',
  'opendatefood': '개업일',
  'opentimefood': '영업시간',
  'restdatefood': '쉬는날',
  'discountinfofood': '할인정보',
  'chkcreditcardfood': '신용카드 가능 정보',
  'reservationfood': '예약 안내',
  'lcnsno': '인허가번호',
};
